title: Recipe Manager
description: Recipe Management app for Linux written in Vala/GTK+3.0, supports localisation and smart unit conversions.
show_downloads: true
theme:
categories: [ sidebar, gallery ]
author: Szymon ≈Åopaciuk
baseurl: /RecipeManager
logopath: /assets/img/lasagna.svg
gems:
  - jekyll-last-modified-at
